version: '3.1'
services:
  pagamentodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=lanchonete
    ports:
      - "27017:27017"
    networks:
      - pagamento-network
  pagamentoapp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - pagamentodb
    networks:
      - pagamento-network
networks:
  pagamento-network:
volumes:
  pagamento-data: