version: '3.1'
services:
  pagamentodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    expose:
      - '27017'
    networks:
      - pagamento-network
  pagamentoapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_DATA_MONGODB_HOST: localhost
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: lanchonete
    depends_on:
      - pagamentodb
    links:
      - pagamentodb
    networks:
      - pagamento-network
networks:
  pagamento-network:
volumes:
  pagamento-data: